INSERT INTO category (name) values ('Electronics');
INSERT INTO category (name) values ('Appliances');
INSERT INTO category (name) values ('Computers');
INSERT INTO category (name) values ('Childen''s goods');
INSERT INTO category (name) values ('Pet supplies');
INSERT INTO category (name) values ('Beauty and hygiene');
INSERT INTO category (name) values ('Pharmacy');
INSERT INTO category (name) values ('Books');
INSERT INTO category (name) values ('Sports and recreation');

INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 908, 7);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 375, 4);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 164, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 791, 3);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 346, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 922, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 364, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 459, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 316, 6);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 453, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 778, 8);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 937, 6);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 696, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 131, 8);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 35, 1);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 584, 3);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 140, 5);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 718, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 688, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 163, 5);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 994, 6);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 432, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 195, 2);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 887, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 74, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 733, 5);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 820, 7);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 422, 6);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 468, 1);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 702, 6);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 839, 1);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 865, 3);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 856, 8);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 31, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 843, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 676, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 157, 5);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 209, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 504, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 139, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 130, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 154, 5);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 469, 1);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 290, 5);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 204, 7);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 872, 6);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 516, 6);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 337, 8);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 5, 6);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 789, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 907, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 14, 7);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 253, 7);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 109, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 529, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 965, 1);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 305, 7);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 131, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 91, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 282, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 444, 1);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 474, 1);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 762, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 886, 4);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 854, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 768, 9);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 577, 7);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 15, 2);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 112, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 742, 3);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 175, 4);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 802, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 792, 2);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 443, 2);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 639, 5);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 700, 8);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 592, 4);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 999, 3);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 71, 6);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 462, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 918, 7);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 795, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 700, 3);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 166, 1);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 551, 5);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 238, 6);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 745, 4);
INSERT INTO goods (name, description, price, category_id) values ('desired product', 'description', 497, 2);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 933, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 947, 8);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 271, 6);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 350, 2);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 474, 8);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 510, 7);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 501, 8);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 477, 3);
INSERT INTO goods (name, description, price, category_id) values ('some thing', 'description', 601, 4);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 735, 2);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 580, 5);
INSERT INTO goods (name, description, price, category_id) values ('abstract goods', 'description', 302, 8);

INSERT INTO storage (row, place, amount, goods_id) values (1, 1, 149, 1);
INSERT INTO storage (row, place, amount, goods_id) values (1, 2, 132, 2);
INSERT INTO storage (row, place, amount, goods_id) values (1, 3, 991, 3);
INSERT INTO storage (row, place, amount, goods_id) values (1, 4, 591, 4);
INSERT INTO storage (row, place, amount, goods_id) values (1, 5, 541, 5);
INSERT INTO storage (row, place, amount, goods_id) values (1, 6, 486, 6);
INSERT INTO storage (row, place, amount, goods_id) values (1, 7, 823, 7);
INSERT INTO storage (row, place, amount, goods_id) values (1, 8, 411, 8);
INSERT INTO storage (row, place, amount, goods_id) values (1, 9, 309, 9);
INSERT INTO storage (row, place, amount, goods_id) values (1, 10, 358, 10);
INSERT INTO storage (row, place, amount, goods_id) values (2, 1, 250, 11);
INSERT INTO storage (row, place, amount, goods_id) values (2, 2, 499, 12);
INSERT INTO storage (row, place, amount, goods_id) values (2, 3, 219, 13);
INSERT INTO storage (row, place, amount, goods_id) values (2, 4, 679, 14);
INSERT INTO storage (row, place, amount, goods_id) values (2, 5, 909, 15);
INSERT INTO storage (row, place, amount, goods_id) values (2, 6, 999, 16);
INSERT INTO storage (row, place, amount, goods_id) values (2, 7, 107, 17);
INSERT INTO storage (row, place, amount, goods_id) values (2, 8, 752, 18);
INSERT INTO storage (row, place, amount, goods_id) values (2, 9, 204, 19);
INSERT INTO storage (row, place, amount, goods_id) values (2, 10, 364, 20);
INSERT INTO storage (row, place, amount, goods_id) values (3, 1, 544, 21);
INSERT INTO storage (row, place, amount, goods_id) values (3, 2, 301, 22);
INSERT INTO storage (row, place, amount, goods_id) values (3, 3, 731, 23);
INSERT INTO storage (row, place, amount, goods_id) values (3, 4, 155, 24);
INSERT INTO storage (row, place, amount, goods_id) values (3, 5, 651, 25);
INSERT INTO storage (row, place, amount, goods_id) values (3, 6, 353, 26);
INSERT INTO storage (row, place, amount, goods_id) values (3, 7, 476, 27);
INSERT INTO storage (row, place, amount, goods_id) values (3, 8, 609, 28);
INSERT INTO storage (row, place, amount, goods_id) values (3, 9, 388, 29);
INSERT INTO storage (row, place, amount, goods_id) values (3, 10, 74, 30);
INSERT INTO storage (row, place, amount, goods_id) values (4, 1, 450, 31);
INSERT INTO storage (row, place, amount, goods_id) values (4, 2, 99, 32);
INSERT INTO storage (row, place, amount, goods_id) values (4, 3, 741, 33);
INSERT INTO storage (row, place, amount, goods_id) values (4, 4, 345, 34);
INSERT INTO storage (row, place, amount, goods_id) values (4, 5, 228, 35);
INSERT INTO storage (row, place, amount, goods_id) values (4, 6, 115, 36);
INSERT INTO storage (row, place, amount, goods_id) values (4, 7, 55, 37);
INSERT INTO storage (row, place, amount, goods_id) values (4, 8, 989, 38);
INSERT INTO storage (row, place, amount, goods_id) values (4, 9, 125, 39);
INSERT INTO storage (row, place, amount, goods_id) values (4, 10, 355, 40);
INSERT INTO storage (row, place, amount, goods_id) values (5, 1, 931, 41);
INSERT INTO storage (row, place, amount, goods_id) values (5, 2, 75, 42);
INSERT INTO storage (row, place, amount, goods_id) values (5, 3, 40, 43);
INSERT INTO storage (row, place, amount, goods_id) values (5, 4, 117, 44);
INSERT INTO storage (row, place, amount, goods_id) values (5, 5, 379, 45);
INSERT INTO storage (row, place, amount, goods_id) values (5, 6, 444, 46);
INSERT INTO storage (row, place, amount, goods_id) values (5, 7, 544, 47);
INSERT INTO storage (row, place, amount, goods_id) values (5, 8, 924, 48);
INSERT INTO storage (row, place, amount, goods_id) values (5, 9, 601, 49);
INSERT INTO storage (row, place, amount, goods_id) values (5, 10, 699, 50);
INSERT INTO storage (row, place, amount, goods_id) values (6, 1, 814, 51);
INSERT INTO storage (row, place, amount, goods_id) values (6, 2, 339, 52);
INSERT INTO storage (row, place, amount, goods_id) values (6, 3, 765, 53);
INSERT INTO storage (row, place, amount, goods_id) values (6, 4, 401, 54);
INSERT INTO storage (row, place, amount, goods_id) values (6, 5, 916, 55);
INSERT INTO storage (row, place, amount, goods_id) values (6, 6, 880, 56);
INSERT INTO storage (row, place, amount, goods_id) values (6, 7, 164, 57);
INSERT INTO storage (row, place, amount, goods_id) values (6, 8, 399, 58);
INSERT INTO storage (row, place, amount, goods_id) values (6, 9, 918, 59);
INSERT INTO storage (row, place, amount, goods_id) values (6, 10, 853, 60);
INSERT INTO storage (row, place, amount, goods_id) values (7, 1, 603, 61);
INSERT INTO storage (row, place, amount, goods_id) values (7, 2, 631, 62);
INSERT INTO storage (row, place, amount, goods_id) values (7, 3, 848, 63);
INSERT INTO storage (row, place, amount, goods_id) values (7, 4, 787, 64);
INSERT INTO storage (row, place, amount, goods_id) values (7, 5, 955, 65);
INSERT INTO storage (row, place, amount, goods_id) values (7, 6, 808, 66);
INSERT INTO storage (row, place, amount, goods_id) values (7, 7, 402, 67);
INSERT INTO storage (row, place, amount, goods_id) values (7, 8, 235, 68);
INSERT INTO storage (row, place, amount, goods_id) values (7, 9, 255, 69);
INSERT INTO storage (row, place, amount, goods_id) values (7, 10, 188, 70);
INSERT INTO storage (row, place, amount, goods_id) values (8, 1, 745, 71);
INSERT INTO storage (row, place, amount, goods_id) values (8, 2, 922, 72);
INSERT INTO storage (row, place, amount, goods_id) values (8, 3, 697, 73);
INSERT INTO storage (row, place, amount, goods_id) values (8, 4, 159, 74);
INSERT INTO storage (row, place, amount, goods_id) values (8, 5, 279, 75);
INSERT INTO storage (row, place, amount, goods_id) values (8, 6, 815, 76);
INSERT INTO storage (row, place, amount, goods_id) values (8, 7, 738, 77);
INSERT INTO storage (row, place, amount, goods_id) values (8, 8, 998, 78);
INSERT INTO storage (row, place, amount, goods_id) values (8, 9, 770, 79);
INSERT INTO storage (row, place, amount, goods_id) values (8, 10, 317, 80);
INSERT INTO storage (row, place, amount, goods_id) values (9, 1, 184, 81);
INSERT INTO storage (row, place, amount, goods_id) values (9, 2, 146, 82);
INSERT INTO storage (row, place, amount, goods_id) values (9, 3, 130, 83);
INSERT INTO storage (row, place, amount, goods_id) values (9, 4, 800, 84);
INSERT INTO storage (row, place, amount, goods_id) values (9, 5, 545, 85);
INSERT INTO storage (row, place, amount, goods_id) values (9, 6, 688, 86);
INSERT INTO storage (row, place, amount, goods_id) values (9, 7, 836, 87);
INSERT INTO storage (row, place, amount, goods_id) values (9, 8, 918, 88);
INSERT INTO storage (row, place, amount, goods_id) values (9, 9, 6, 89);
INSERT INTO storage (row, place, amount, goods_id) values (9, 10, 550, 90);
INSERT INTO storage (row, place, amount, goods_id) values (10, 1, 564, 91);
INSERT INTO storage (row, place, amount, goods_id) values (10, 2, 795, 92);
INSERT INTO storage (row, place, amount, goods_id) values (10, 3, 971, 93);
INSERT INTO storage (row, place, amount, goods_id) values (10, 4, 548, 94);
INSERT INTO storage (row, place, amount, goods_id) values (10, 5, 911, 95);
INSERT INTO storage (row, place, amount, goods_id) values (10, 6, 800, 96);
INSERT INTO storage (row, place, amount, goods_id) values (10, 7, 875, 97);
INSERT INTO storage (row, place, amount, goods_id) values (10, 8, 20, 98);
INSERT INTO storage (row, place, amount, goods_id) values (10, 9, 502, 99);
INSERT INTO storage (row, place, amount, goods_id) values (10, 10, 986, 100);

